# Install a role for java 
- src: geerlingguy.java

# Install a role for docker
- src: geerlingguy.docker

# Install a role for gitlab/gitlab-runner
- src: https://github.com/HP41/ansible-docker-gitlab.git
